export interface EndpointEntry {
  name: string;
  url_template: string;
  category: string;
}

export function getAllEndpoints(): EndpointEntry[] {
  return [
    ...getWhoisEndpoints(),
    ...getDnsEndpoints(),
    ...getSeoAnalyzerEndpoints(),
    ...getSpeedTestEndpoints(),
    ...getSecurityEndpoints(),
    ...getWebArchiveEndpoints(),
    ...getWebsiteInfoEndpoints(),
    ...getPingEndpoints(),
    ...getSocialBookmarkEndpoints(),
    ...getDirectoryEndpoints(),
    ...getGeneralEndpoints(),
    ...getLLMEndpoints(),
  ];
}

function getWhoisEndpoints(): EndpointEntry[] {
  return [
    { name: 'Who.is', url_template: 'https://who.is/whois/{DOMAIN}', category: 'whois' },
    { name: 'WhoisRequest', url_template: 'https://whoisrequest.com/whois/{DOMAIN}', category: 'whois' },
    { name: 'ICANN WHOIS', url_template: 'https://lookup.icann.org/en/lookup?name={DOMAIN}', category: 'whois' },
    { name: 'DomainTools', url_template: 'https://whois.domaintools.com/{DOMAIN}', category: 'whois' },
    { name: 'Whois.com', url_template: 'https://www.whois.com/whois/{DOMAIN}', category: 'whois' },
    { name: 'DomainBigData', url_template: 'https://domainbigdata.com/{DOMAIN}', category: 'whois' },
    { name: 'Whoxy', url_template: 'https://www.whoxy.com/{DOMAIN}', category: 'whois' },
    { name: 'EasyWhois', url_template: 'https://www.easywhois.com/{DOMAIN}', category: 'whois' },
    { name: 'Gwhois', url_template: 'https://gwhois.org/{DOMAIN}', category: 'whois' },
    { name: 'WhoisHosting', url_template: 'https://www.whoishostingthis.com/{DOMAIN}', category: 'whois' },
    { name: 'HostAdvice WHOIS', url_template: 'https://hostadvice.com/tools/whois/{DOMAIN}', category: 'whois' },
    { name: 'WHOISology', url_template: 'https://whoisology.com/{DOMAIN}', category: 'whois' },
    { name: 'DomainWatch', url_template: 'https://domainwat.ch/site/{DOMAIN}', category: 'whois' },
    { name: 'WhoisXY', url_template: 'https://www.whoisxy.com/{DOMAIN}', category: 'whois' },
    { name: 'DomainIQ', url_template: 'https://www.domainiq.com/snapshot/{DOMAIN}', category: 'whois' },
    { name: 'Marcaria WHOIS', url_template: 'https://whois.marcaria.com/en/result?domain={DOMAIN}', category: 'whois' },
    { name: 'IANA WHOIS', url_template: 'https://www.iana.org/whois?q={DOMAIN}', category: 'whois' },
    { name: 'Domfind', url_template: 'https://www.domfind.com/{DOMAIN}', category: 'whois' },
    { name: 'ThatsThem WHOIS', url_template: 'https://thatsthem.com/whois/{DOMAIN}', category: 'whois' },
    { name: 'WhoisFreaks', url_template: 'https://whoisfreaks.com/tools/whois/lookup/{DOMAIN}', category: 'whois' },
    { name: 'WhoAPI', url_template: 'https://whoapi.com/domain/{DOMAIN}', category: 'whois' },
    { name: 'Namecheap WHOIS', url_template: 'https://www.namecheap.com/domains/whois/result?domain={DOMAIN}', category: 'whois' },
    { name: 'GoDaddy WHOIS', url_template: 'https://www.godaddy.com/whois/results.aspx?domain={DOMAIN}', category: 'whois' },
    { name: 'Google Domains', url_template: 'https://domains.google.com/registrar?s={DOMAIN}', category: 'whois' },
    { name: 'Register.com WHOIS', url_template: 'https://www.register.com/whois.rcmx?domain={DOMAIN}', category: 'whois' },
    { name: 'Name.com WHOIS', url_template: 'https://www.name.com/whois/{DOMAIN}', category: 'whois' },
    { name: 'Dynadot WHOIS', url_template: 'https://www.dynadot.com/domain/search?domain={DOMAIN}', category: 'whois' },
    { name: 'Porkbun WHOIS', url_template: 'https://porkbun.com/products/domains?search={DOMAIN}', category: 'whois' },
    { name: 'Hover WHOIS', url_template: 'https://www.hover.com/domains/results?q={DOMAIN}', category: 'whois' },
    { name: 'Gandi WHOIS', url_template: 'https://www.gandi.net/whois?search={DOMAIN}', category: 'whois' },
    { name: 'DomainScope', url_template: 'https://www.domainscope.com/whois/{DOMAIN}', category: 'whois' },
    { name: 'Whois365', url_template: 'https://whois365.com/domain/{DOMAIN}', category: 'whois' },
    { name: 'IPvoid WHOIS', url_template: 'https://www.ipvoid.com/whois/{DOMAIN}', category: 'whois' },
    { name: 'UltraTools WHOIS', url_template: 'https://www.ultratools.com/tools/whoisResult?domain={DOMAIN}', category: 'whois' },
    { name: 'Robtex WHOIS', url_template: 'https://www.robtex.com/dns-lookup/{DOMAIN}', category: 'whois' },
    { name: 'DomainData', url_template: 'https://domaindata.io/{DOMAIN}', category: 'whois' },
    { name: 'NameStat', url_template: 'https://namestat.org/d/{DOMAIN}', category: 'whois' },
    { name: 'TLD List WHOIS', url_template: 'https://tld-list.com/whois/{DOMAIN}', category: 'whois' },
    { name: 'DomainCodex', url_template: 'https://www.domaincodex.com/search.php?q={DOMAIN}', category: 'whois' },
    { name: 'Whois24', url_template: 'https://www.whois24.net/{DOMAIN}', category: 'whois' },
    { name: 'WebAnalyzer WHOIS', url_template: 'https://wa-com.com/{DOMAIN}', category: 'whois' },
    { name: 'DomainCrawler', url_template: 'https://domaincrawler.com/domain/{DOMAIN}', category: 'whois' },
    { name: 'WhoisMind', url_template: 'https://whoismind.com/{DOMAIN}', category: 'whois' },
    { name: 'DomainHistory', url_template: 'https://whois-history.whoisxmlapi.com/api/v1?domainName={DOMAIN}', category: 'whois' },
    { name: 'DNSTrails WHOIS', url_template: 'https://securitytrails.com/domain/{DOMAIN}/whois', category: 'whois' },
    { name: 'WhoisDS', url_template: 'https://www.whoisds.com/whois/{DOMAIN}', category: 'whois' },
    { name: 'Registrar WHOIS', url_template: 'https://registrar.verisign-grs.com/regist/registrar/{DOMAIN}', category: 'whois' },
    { name: 'RIPE WHOIS', url_template: 'https://apps.db.ripe.net/db-web-ui/query?searchtext={DOMAIN}', category: 'whois' },
    { name: 'ARIN WHOIS', url_template: 'https://whois.arin.net/rest/net?q={DOMAIN}', category: 'whois' },
    { name: 'APNIC WHOIS', url_template: 'https://wq.apnic.net/apnic-bin/whois.pl?searchtext={DOMAIN}', category: 'whois' },
    { name: 'LACNIC WHOIS', url_template: 'https://query.milacnic.lacnic.net/search?q={DOMAIN}', category: 'whois' },
    { name: 'AfriNIC WHOIS', url_template: 'https://afrinic.net/whois?searchtext={DOMAIN}', category: 'whois' },
    { name: 'DomainAvail', url_template: 'https://instantdomainsearch.com/search/domains?q={DOMAIN}', category: 'whois' },
    { name: 'NameBio', url_template: 'https://namebio.com/{DOMAIN}', category: 'whois' },
    { name: 'Sedo WHOIS', url_template: 'https://sedo.com/search/details/?domain={DOMAIN}', category: 'whois' },
    { name: 'Afternic', url_template: 'https://www.afternic.com/search?k={DOMAIN}', category: 'whois' },
    { name: 'DomainPunch', url_template: 'https://domainpunch.com/whois/{DOMAIN}', category: 'whois' },
    { name: 'NetCraft WHOIS', url_template: 'https://searchdns.netcraft.com/?restriction=site+contains&host={DOMAIN}', category: 'whois' },
    { name: 'DomainSherpa', url_template: 'https://www.domainsherpa.com/tools/whois/?domain={DOMAIN}', category: 'whois' },
    { name: 'Whoisology2', url_template: 'https://whoisology.com/#advanced/domain={DOMAIN}', category: 'whois' },
    { name: 'DomainsDB', url_template: 'https://domainsdb.info/?search={DOMAIN}', category: 'whois' },
    { name: 'DomainLore', url_template: 'https://domainlore.co.uk/whois/{DOMAIN}', category: 'whois' },
    { name: 'Hexillion WHOIS', url_template: 'https://hexillion.com/rf/RequestData.aspx?ip={DOMAIN}', category: 'whois' },
    { name: 'WebHosting.info', url_template: 'https://whois.webhosting.info/{DOMAIN}', category: 'whois' },
    { name: 'DomainStatus', url_template: 'https://www.domainstatus.com/whois/{DOMAIN}', category: 'whois' },
    { name: 'SmartWhois', url_template: 'https://www.smartwhois.com/whois/{DOMAIN}', category: 'whois' },
    { name: 'WebWhois', url_template: 'https://webwhois.verisign.com/webwhois-ui/index.jsp?domain={DOMAIN}', category: 'whois' },
    { name: 'Centralops WHOIS', url_template: 'https://centralops.net/co/DomainDossier.aspx?addr={DOMAIN}&dom_whois=true', category: 'whois' },
    { name: 'DNSStuff WHOIS', url_template: 'https://tools.dnsstuff.com/tools/index.php?tool=whois&domain={DOMAIN}', category: 'whois' },
    { name: 'DomainPulse', url_template: 'https://domainpulse.com/{DOMAIN}', category: 'whois' },
    { name: 'HostTracker WHOIS', url_template: 'https://www.host-tracker.com/en/ic/whois/{DOMAIN}', category: 'whois' },
    { name: 'SuperTool WHOIS', url_template: 'https://supertool.com/whois/{DOMAIN}', category: 'whois' },
    { name: 'LookupServer', url_template: 'https://www.lookupserver.com/whois/{DOMAIN}', category: 'whois' },
    { name: 'WhoisXML Lookup', url_template: 'https://whois.whoisxmlapi.com/lookup?domainName={DOMAIN}', category: 'whois' },
    { name: 'DomainTools History', url_template: 'https://research.domaintools.com/research/hosting-history/?q={DOMAIN}', category: 'whois' },
    { name: 'WhoIsOwner', url_template: 'https://whoisowner.com/{DOMAIN}', category: 'whois' },
    { name: 'WhoIsIP', url_template: 'https://www.whoisip.com/{DOMAIN}', category: 'whois' },
    { name: 'DomainBrain', url_template: 'https://domainbrain.com/whois/{DOMAIN}', category: 'whois' },
    { name: 'WhoisServer', url_template: 'https://whoisserver.com/whois/{DOMAIN}', category: 'whois' },
    { name: 'NetSol WHOIS', url_template: 'https://www.networksolutions.com/whois/results.jsp?domain={DOMAIN}', category: 'whois' },
    { name: '1and1 WHOIS', url_template: 'https://www.ionos.com/tools/domain-availability-check?domain={DOMAIN}', category: 'whois' },
    { name: 'Bluehost WHOIS', url_template: 'https://www.bluehost.com/hosting/whois?domain={DOMAIN}', category: 'whois' },
    { name: 'HostGator WHOIS', url_template: 'https://www.hostgator.com/whois/?domain={DOMAIN}', category: 'whois' },
    { name: 'InMotion WHOIS', url_template: 'https://www.inmotionhosting.com/whois/?domain={DOMAIN}', category: 'whois' },
    { name: 'SiteGround WHOIS', url_template: 'https://www.siteground.com/whois/?domain={DOMAIN}', category: 'whois' },
    { name: 'A2Hosting WHOIS', url_template: 'https://www.a2hosting.com/whois/?domain={DOMAIN}', category: 'whois' },
    { name: 'DreamHost WHOIS', url_template: 'https://www.dreamhost.com/domains/whois/?domain={DOMAIN}', category: 'whois' },
    { name: 'Hostinger WHOIS', url_template: 'https://www.hostinger.com/whois?domain={DOMAIN}', category: 'whois' },
    { name: 'Cloudflare WHOIS', url_template: 'https://www.cloudflare.com/whois/?domain={DOMAIN}', category: 'whois' },
  ];
}

function getDnsEndpoints(): EndpointEntry[] {
  return [
    { name: 'WhoisXML DNS', url_template: 'https://dns-lookup.whoisxmlapi.com/?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'ViewDNS', url_template: 'https://viewdns.info/whois/?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'DNSlytics', url_template: 'https://dnslytics.com/domain/{DOMAIN}', category: 'dns_lookup' },
    { name: 'SecurityTrails', url_template: 'https://securitytrails.com/domain/{DOMAIN}', category: 'dns_lookup' },
    { name: 'DNSdumpster', url_template: 'https://dnsdumpster.com/?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'MXToolbox DNS', url_template: 'https://mxtoolbox.com/SuperTool.aspx?action=dns:{DOMAIN}', category: 'dns_lookup' },
    { name: 'IntoDNS', url_template: 'https://intodns.com/{DOMAIN}', category: 'dns_lookup' },
    { name: 'DNSChecker', url_template: 'https://dnschecker.org/all-dns-records-of-domain.php?query={DOMAIN}', category: 'dns_lookup' },
    { name: 'WhatMyDNS', url_template: 'https://www.whatsmydns.net/#A/{DOMAIN}', category: 'dns_lookup' },
    { name: 'CompleteDNS', url_template: 'https://completedns.com/dns-history/{DOMAIN}', category: 'dns_lookup' },
    { name: 'DNSWatch', url_template: 'https://www.dnswatch.info/dns/dnslookup?la=en&host={DOMAIN}', category: 'dns_lookup' },
    { name: 'DNSViz', url_template: 'https://dnsviz.net/d/{DOMAIN}/analyze/', category: 'dns_lookup' },
    { name: 'MXToolbox MX', url_template: 'https://mxtoolbox.com/SuperTool.aspx?action=mx:{DOMAIN}', category: 'dns_lookup' },
    { name: 'Spamhaus DNS', url_template: 'https://check.spamhaus.org/listed/?searchterm={DOMAIN}', category: 'dns_lookup' },
    { name: 'Netcraft DNS', url_template: 'https://toolbar.netcraft.com/site_report?url={DOMAIN}', category: 'dns_lookup' },
    { name: 'DNSInspect', url_template: 'https://www.dnsinspect.com/{DOMAIN}', category: 'dns_lookup' },
    { name: 'ZoneMaster', url_template: 'https://www.zonemaster.net/domain_check?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'DNSTrails', url_template: 'https://securitytrails.com/domain/{DOMAIN}/dns', category: 'dns_lookup' },
    { name: 'LeafDNS', url_template: 'https://leafdns.com/domain/{DOMAIN}', category: 'dns_lookup' },
    { name: 'Hackertarget DNS', url_template: 'https://hackertarget.com/dns-lookup/?q={DOMAIN}', category: 'dns_lookup' },
    { name: 'ToolBox DNS', url_template: 'https://toolbox.googleapps.com/apps/dig/#ANY/{DOMAIN}', category: 'dns_lookup' },
    { name: 'DNSQuery', url_template: 'https://www.dnsqueries.com/en/domain_check.php?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'NsLookup', url_template: 'https://www.nslookup.io/domains/{DOMAIN}/dns-records/', category: 'dns_lookup' },
    { name: 'DomainInfo', url_template: 'https://domain.glass/{DOMAIN}', category: 'dns_lookup' },
    { name: 'DigiCert DNS', url_template: 'https://www.digicert.com/help/?host={DOMAIN}', category: 'dns_lookup' },
    { name: 'ClouDNS Lookup', url_template: 'https://www.cloudns.net/tools/dns-lookup/{DOMAIN}', category: 'dns_lookup' },
    { name: 'BuddyDNS Check', url_template: 'https://www.buddyns.com/delegation-lab/?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'UltraTools DNS', url_template: 'https://www.ultratools.com/tools/dnsLookupResult?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'DNSMap', url_template: 'https://dnsmap.io/#/{DOMAIN}', category: 'dns_lookup' },
    { name: 'Constellix DNS', url_template: 'https://tools.constellix.com/dns-lookup/{DOMAIN}', category: 'dns_lookup' },
    { name: 'IPIP DNS', url_template: 'https://en.ipip.net/dns.php?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'Kloth DNS', url_template: 'https://www.kloth.net/services/nslookup.php?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'MyDNSTools', url_template: 'https://www.mydnstools.info/dns/{DOMAIN}', category: 'dns_lookup' },
    { name: 'DNSRecord', url_template: 'https://www.dnsrecord.io/?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'FindDNS Host', url_template: 'https://www.finddns.net/whois/{DOMAIN}', category: 'dns_lookup' },
    { name: 'Debouncer MX', url_template: 'https://tools.debouncer.com/mx-lookup/{DOMAIN}', category: 'dns_lookup' },
    { name: 'MXLookup', url_template: 'https://www.mxlookup.com/{DOMAIN}', category: 'dns_lookup' },
    { name: 'MailhardenerMX', url_template: 'https://www.mailhardener.com/tools/domain-dns-check?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'SPFCheck', url_template: 'https://www.spf-record.com/spf-lookup/{DOMAIN}', category: 'dns_lookup' },
    { name: 'DMARCian', url_template: 'https://dmarcian.com/domain-checker/?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'EasyDMARC', url_template: 'https://easydmarc.com/tools/dmarc-lookup?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'MXRoute Check', url_template: 'https://www.mail-tester.com/test?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'Viewdns Reverse', url_template: 'https://viewdns.info/reverseip/?host={DOMAIN}&t=1', category: 'dns_lookup' },
    { name: 'Viewdns Portscan', url_template: 'https://viewdns.info/portscan/?host={DOMAIN}', category: 'dns_lookup' },
    { name: 'Viewdns Headers', url_template: 'https://viewdns.info/httpheaders/?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'Viewdns IP History', url_template: 'https://viewdns.info/iphistory/?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'Viewdns DNS Record', url_template: 'https://viewdns.info/dnsrecord/?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'Viewdns DNS Report', url_template: 'https://viewdns.info/dnsreport/?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'Viewdns Traceroute', url_template: 'https://viewdns.info/traceroute/?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'Viewdns Reverse NS', url_template: 'https://viewdns.info/reversens/?ns={DOMAIN}', category: 'dns_lookup' },
    { name: 'Viewdns DNS Propagation', url_template: 'https://viewdns.info/propagation/?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'Hackertarget Reverse', url_template: 'https://hackertarget.com/reverse-dns-lookup/?q={DOMAIN}', category: 'dns_lookup' },
    { name: 'Hackertarget Traceroute', url_template: 'https://hackertarget.com/online-traceroute/?q={DOMAIN}', category: 'dns_lookup' },
    { name: 'Hackertarget Zone Transfer', url_template: 'https://hackertarget.com/zone-transfer/?q={DOMAIN}', category: 'dns_lookup' },
    { name: 'Hackertarget Whois', url_template: 'https://hackertarget.com/whois-lookup/?q={DOMAIN}', category: 'dns_lookup' },
    { name: 'Hackertarget HTTP Headers', url_template: 'https://hackertarget.com/http-header-check/?q={DOMAIN}', category: 'dns_lookup' },
    { name: 'Hackertarget Page Links', url_template: 'https://hackertarget.com/extract-links/?q={DOMAIN}', category: 'dns_lookup' },
    { name: 'Hackertarget Shared DNS', url_template: 'https://hackertarget.com/find-shared-dns-servers/?q={DOMAIN}', category: 'dns_lookup' },
    { name: 'Nettools DNS', url_template: 'https://network-tools.com/nslookup/{DOMAIN}', category: 'dns_lookup' },
    { name: 'IPFingerprints DNS', url_template: 'https://www.ipfingerprints.com/portscan.php?host={DOMAIN}', category: 'dns_lookup' },
    { name: 'SubnetOnline DNS', url_template: 'https://www.subnetonline.com/pages/network-tools/online-dns-lookup.php?q={DOMAIN}', category: 'dns_lookup' },
    { name: 'CentralOps DNS', url_template: 'https://centralops.net/co/DomainDossier.aspx?addr={DOMAIN}&dom_dns=true', category: 'dns_lookup' },
    { name: 'NetworkCalc DNS', url_template: 'https://networkcalc.com/dns-lookup/{DOMAIN}', category: 'dns_lookup' },
    { name: 'DNSspy', url_template: 'https://dnsspy.io/scan/{DOMAIN}', category: 'dns_lookup' },
    { name: 'Zonecut DNS', url_template: 'https://zonecut.net/dns/?q={DOMAIN}', category: 'dns_lookup' },
    { name: 'IPAddress DNS', url_template: 'https://www.ipaddress.com/site/{DOMAIN}', category: 'dns_lookup' },
    { name: 'IPLocation DNS', url_template: 'https://www.iplocation.net/?query={DOMAIN}', category: 'dns_lookup' },
    { name: 'BGP DNS', url_template: 'https://bgp.he.net/dns/{DOMAIN}', category: 'dns_lookup' },
    { name: 'RIPEstat', url_template: 'https://stat.ripe.net/{DOMAIN}', category: 'dns_lookup' },
    { name: 'DNSLog', url_template: 'https://dnslog.cn/getdomain.php?t={DOMAIN}', category: 'dns_lookup' },
    { name: 'MassDNS', url_template: 'https://massdns.io/domain/{DOMAIN}', category: 'dns_lookup' },
    { name: 'DNSGoodies', url_template: 'https://dnsgoodies.com/{DOMAIN}', category: 'dns_lookup' },
    { name: 'NeutrinoDNS', url_template: 'https://www.neutrinoapi.com/api/host-reputation?host={DOMAIN}', category: 'dns_lookup' },
    { name: 'DNSLookupTool', url_template: 'https://dnslookuptool.com/{DOMAIN}', category: 'dns_lookup' },
    { name: 'DNSTools.ws', url_template: 'https://dnstools.ws/lookup/{DOMAIN}/', category: 'dns_lookup' },
    { name: 'HostingChecker', url_template: 'https://hostingchecker.com/check/{DOMAIN}', category: 'dns_lookup' },
    { name: 'HostingDetector', url_template: 'https://www.hostingdetector.com/?domain={DOMAIN}', category: 'dns_lookup' },
    { name: 'SiteChecker DNS', url_template: 'https://sitechecker.pro/dns-check/?url={DOMAIN}', category: 'dns_lookup' },
    { name: 'Pentest Tools DNS', url_template: 'https://pentest-tools.com/information-gathering/dns-lookup-online?domain={DOMAIN}', category: 'dns_lookup' },
  ];
}

function getSeoAnalyzerEndpoints(): EndpointEntry[] {
  return [
    { name: 'Ahrefs Authority', url_template: 'https://ahrefs.com/website-authority-checker/?input={DOMAIN}', category: 'seo_analyzer' },
    { name: 'SiteChecker SEO', url_template: 'https://sitechecker.pro/app/main/project?input=https%3A%2F%2F{DOMAIN}', category: 'seo_analyzer' },
    { name: 'Moz Domain Analysis', url_template: 'https://moz.com/domain-analysis?site={DOMAIN}', category: 'seo_analyzer' },
    { name: 'SEMrush Overview', url_template: 'https://www.semrush.com/analytics/overview/?q={DOMAIN}', category: 'seo_analyzer' },
    { name: 'Ubersuggest', url_template: 'https://app.neilpatel.com/en/seo_analyzer/site_audit?domain={DOMAIN}', category: 'seo_analyzer' },
    { name: 'SimilarWeb', url_template: 'https://www.similarweb.com/website/{DOMAIN}/', category: 'seo_analyzer' },
    { name: 'Alexa', url_template: 'https://www.alexa.com/siteinfo/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'Majestic', url_template: 'https://majestic.com/reports/site-explorer?q={DOMAIN}', category: 'seo_analyzer' },
    { name: 'SEOptimer', url_template: 'https://www.seoptimer.com/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'WebPageTest', url_template: 'https://www.webpagetest.org/result/?url=https://{DOMAIN}', category: 'seo_analyzer' },
    { name: 'Woorank', url_template: 'https://www.woorank.com/en/www/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'Nibbler', url_template: 'https://nibbler.silktide.com/en/reports/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'SEObility', url_template: 'https://freetools.seobility.net/en/seocheck/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'SEOSiteCheckup', url_template: 'https://seositecheckup.com/analysis/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'SiteLiner', url_template: 'https://www.siteliner.com/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'Dareboost', url_template: 'https://www.dareboost.com/en/report/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'SEOquake Check', url_template: 'https://www.seoquake.com/index.html?query={DOMAIN}', category: 'seo_analyzer' },
    { name: 'SpyFu', url_template: 'https://www.spyfu.com/overview/domain?query={DOMAIN}', category: 'seo_analyzer' },
    { name: 'SERPstat', url_template: 'https://serpstat.com/domains/?query={DOMAIN}', category: 'seo_analyzer' },
    { name: 'RankWatch', url_template: 'https://www.rankwatch.com/site-audit/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'ContentKing', url_template: 'https://www.contentkingapp.com/dashboard/?domain={DOMAIN}', category: 'seo_analyzer' },
    { name: 'Screaming Frog', url_template: 'https://www.screamingfrog.co.uk/seo-spider/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'Raven Tools', url_template: 'https://raventools.com/site-auditor/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'DeepCrawl', url_template: 'https://www.deepcrawl.com/crawl/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'OnCrawl', url_template: 'https://www.oncrawl.com/project/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'Botify', url_template: 'https://www.botify.com/analysis/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'CognitiveSEO', url_template: 'https://cognitiveseo.com/site-audit/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'LinkResearchTools', url_template: 'https://smart.linkresearchtools.com/link-check/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'MonitorBacklinks', url_template: 'https://monitorbacklinks.com/seo-tools/free-backlink-checker?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'OpenLinkProfiler', url_template: 'https://openlinkprofiler.org/r/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'BacklinkWatch', url_template: 'https://www.backlinkwatch.com/index.php?q={DOMAIN}', category: 'seo_analyzer' },
    { name: 'SmallSEOTools Backlinks', url_template: 'https://smallseotools.com/backlink-checker/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'LinkMiner', url_template: 'https://linkminer.com/check?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'SEOReviewTools', url_template: 'https://www.seoreviewtools.com/website-authority-checker/?url=https://{DOMAIN}', category: 'seo_analyzer' },
    { name: 'SERPChecker', url_template: 'https://mangools.com/free-serp-checker?query={DOMAIN}', category: 'seo_analyzer' },
    { name: 'RankSignals', url_template: 'https://www.ranksignals.com/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'KeywordTool', url_template: 'https://keywordtool.io/search?input={DOMAIN}', category: 'seo_analyzer' },
    { name: 'SearchMetrics', url_template: 'https://suite.searchmetrics.com/en/research/domains/organic?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'iSpionage', url_template: 'https://www.ispionage.com/research/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'AuthoritySpy', url_template: 'https://authorityspy.com/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'SEMRush Backlinks', url_template: 'https://www.semrush.com/analytics/backlinks/overview/?q={DOMAIN}', category: 'seo_analyzer' },
    { name: 'Ahrefs Backlinks', url_template: 'https://ahrefs.com/backlink-checker/?input={DOMAIN}', category: 'seo_analyzer' },
    { name: 'SEOProfiler', url_template: 'https://www.seoprofiler.com/analyze/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'WebMeUp', url_template: 'https://webmeup.com/backlink-tool/report/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'StatsCrop', url_template: 'https://www.statscrop.com/www/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'SiteWorthTraffic', url_template: 'https://www.siteworthtraffic.com/report/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'WebsiteIQ', url_template: 'https://website.informer.com/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'HypeStat', url_template: 'https://hypestat.com/info/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'Quantcast', url_template: 'https://www.quantcast.com/measure/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'TrafficEstimate', url_template: 'https://www.trafficestimate.com/website/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'CompetitorSpy', url_template: 'https://www.competitorspy.com/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'RankRanger', url_template: 'https://www.rankranger.com/site-analysis?domain={DOMAIN}', category: 'seo_analyzer' },
    { name: 'AccuRanker', url_template: 'https://www.accuranker.com/grader/?domain={DOMAIN}', category: 'seo_analyzer' },
    { name: 'SEOmator', url_template: 'https://seomator.com/free-tools/website-audit?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'SEOCentro', url_template: 'https://www.seocentro.com/tools/search-engines/metatag-analyzer.html?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'AnalyzeSEO', url_template: 'https://www.yourwebsitevalue.com/website/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'SiteScore', url_template: 'https://www.site-score.com/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'Zadroweb', url_template: 'https://zadroweb.com/seo-auditor/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'PageScoring', url_template: 'https://www.pagescoring.com/website-speed-test/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'WebsiteGrader', url_template: 'https://website.grader.com/results/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'SiteAnalyzer', url_template: 'https://www.siteanalyzer.com/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'SEOWorkers', url_template: 'https://www.seoworkers.com/tools/analyzer.html?url=https://{DOMAIN}', category: 'seo_analyzer' },
    { name: 'FreeWebSubmission', url_template: 'https://www.freewebsubmission.com/analyze.html?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'RankPay', url_template: 'https://www.rankpay.com/free-seo-audit/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'SEOChat Analyzer', url_template: 'https://tools.seochat.com/tools/site-analysis/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'MySiteAuditor', url_template: 'https://www.mysiteauditor.com/free-report/?domain={DOMAIN}', category: 'seo_analyzer' },
    { name: 'SEOTesterOnline', url_template: 'https://www.seotesteronline.com/seo-checker/{DOMAIN}', category: 'seo_analyzer' },
    { name: 'SortSite Check', url_template: 'https://www.powermapper.com/products/sortsite/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'MetaTags IO', url_template: 'https://metatags.io/?url=https://{DOMAIN}', category: 'seo_analyzer' },
    { name: 'RichResults Test', url_template: 'https://search.google.com/test/rich-results?url=https://{DOMAIN}', category: 'seo_analyzer' },
    { name: 'StructuredData Test', url_template: 'https://validator.schema.org/#url=https%3A%2F%2F{DOMAIN}', category: 'seo_analyzer' },
    { name: 'PageSpeed Insights', url_template: 'https://pagespeed.web.dev/analysis?url=https%3A%2F%2F{DOMAIN}', category: 'seo_analyzer' },
    { name: 'Google Mobile Test', url_template: 'https://search.google.com/test/mobile-friendly?url=https%3A%2F%2F{DOMAIN}', category: 'seo_analyzer' },
    { name: 'Google AMP Test', url_template: 'https://search.google.com/test/amp?url=https%3A%2F%2F{DOMAIN}', category: 'seo_analyzer' },
    { name: 'SchemaMarkup Check', url_template: 'https://www.schemaapp.com/tools/jsonld-schema-generator/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'W3C Validator', url_template: 'https://validator.w3.org/nu/?doc=https%3A%2F%2F{DOMAIN}', category: 'seo_analyzer' },
    { name: 'CSSValidator', url_template: 'https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2F{DOMAIN}', category: 'seo_analyzer' },
    { name: 'WAVE Accessibility', url_template: 'https://wave.webaim.org/report#/https://{DOMAIN}', category: 'seo_analyzer' },
    { name: 'LighthouseReport', url_template: 'https://googlechrome.github.io/lighthouse/viewer/?url=https://{DOMAIN}', category: 'seo_analyzer' },
    { name: 'Varvy SEO', url_template: 'https://varvy.com/tools/seo/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'TechnicalSEO Audit', url_template: 'https://technicalseo.com/tools/robots-txt/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'HeadingsMap', url_template: 'https://www.bing.com/webmaster/tools/markup-validator?url=https://{DOMAIN}', category: 'seo_analyzer' },
    { name: 'Copyscape Check', url_template: 'https://www.copyscape.com/?q={DOMAIN}', category: 'seo_analyzer' },
    { name: 'DupliChecker', url_template: 'https://www.duplichecker.com/domain-authority-checker.php?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'SmallSEOTools DA', url_template: 'https://smallseotools.com/domain-authority-checker/?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'PrePostSEO DA', url_template: 'https://www.prepostseo.com/domain-authority-checker?url={DOMAIN}', category: 'seo_analyzer' },
    { name: 'WebsiteSEOChecker', url_template: 'https://www.websiteseochecker.com/domain-authority-checker/?url={DOMAIN}', category: 'seo_analyzer' },
  ];
}

function getSpeedTestEndpoints(): EndpointEntry[] {
  return [
    { name: 'GTmetrix', url_template: 'https://gtmetrix.com/?url=https%3A%2F%2F{DOMAIN}', category: 'speed_test' },
    { name: 'Pingdom', url_template: 'https://tools.pingdom.com/#/{DOMAIN}', category: 'speed_test' },
    { name: 'KeyCDN Speed', url_template: 'https://tools.keycdn.com/speed?url=https%3A%2F%2F{DOMAIN}', category: 'speed_test' },
    { name: 'DotCom Tools', url_template: 'https://www.dotcom-tools.com/website-speed-test?url={DOMAIN}', category: 'speed_test' },
    { name: 'BitCatcha', url_template: 'https://www.bitcatcha.com/speed-test/?url={DOMAIN}', category: 'speed_test' },
    { name: 'Uptrends Speed', url_template: 'https://www.uptrends.com/tools/website-speed-test?url={DOMAIN}', category: 'speed_test' },
    { name: 'GiftOfSpeed', url_template: 'https://www.giftofspeed.com/?url=https://{DOMAIN}', category: 'speed_test' },
    { name: 'SpeedVitals', url_template: 'https://speedvitals.com/results?url=https://{DOMAIN}', category: 'speed_test' },
    { name: 'DebugBear', url_template: 'https://www.debugbear.com/test/website-speed?url=https://{DOMAIN}', category: 'speed_test' },
    { name: 'IsItWP Speed', url_template: 'https://www.isitwp.com/speed-test/?url=https://{DOMAIN}', category: 'speed_test' },
    { name: 'Sucuri Load', url_template: 'https://performance.sucuri.net/domain/{DOMAIN}', category: 'speed_test' },
    { name: 'SiteSpeed', url_template: 'https://www.sitespeed.io/result/https/{DOMAIN}/', category: 'speed_test' },
    { name: 'Updown.io', url_template: 'https://updown.io/checks/new?url=https://{DOMAIN}', category: 'speed_test' },
    { name: 'Host-Tracker Speed', url_template: 'https://www.host-tracker.com/en/ic/check-speed/{DOMAIN}', category: 'speed_test' },
    { name: 'GeoPeeker', url_template: 'https://geopeeker.com/fetch/?url={DOMAIN}', category: 'speed_test' },
    { name: 'Check-Host', url_template: 'https://check-host.net/check-http?host={DOMAIN}', category: 'speed_test' },
    { name: 'PerfPlanet', url_template: 'https://www.perfplanet.com/test/?url={DOMAIN}', category: 'speed_test' },
    { name: 'Monitis Speed', url_template: 'https://www.monitis.com/speedtest?url={DOMAIN}', category: 'speed_test' },
    { name: 'CatchPoint', url_template: 'https://www.catchpoint.com/speed-test/?url={DOMAIN}', category: 'speed_test' },
    { name: 'YSlow Analysis', url_template: 'https://yslow.org/test/?url=https://{DOMAIN}', category: 'speed_test' },
    { name: 'FreeSpeedTest', url_template: 'https://www.freespeedtest.com/test?url={DOMAIN}', category: 'speed_test' },
    { name: 'SpeedCheck.org', url_template: 'https://www.speedcheck.org/web-speed-test/?url={DOMAIN}', category: 'speed_test' },
    { name: 'Experte Speed', url_template: 'https://www.experte.com/pagespeed?url={DOMAIN}', category: 'speed_test' },
    { name: 'Sematext Speed', url_template: 'https://sematext.com/website-performance-checker/?url={DOMAIN}', category: 'speed_test' },
    { name: 'ThinkWithGoogle', url_template: 'https://www.thinkwithgoogle.com/intl/en-gb/feature/testmysite/?url={DOMAIN}', category: 'speed_test' },
    { name: 'CloudFlare Speed', url_template: 'https://speed.cloudflare.com/?url={DOMAIN}', category: 'speed_test' },
    { name: 'Varvy Speed', url_template: 'https://varvy.com/pagespeed/?url=https://{DOMAIN}', category: 'speed_test' },
    { name: 'Yellow Lab Tools', url_template: 'https://yellowlab.tools/result?url=https://{DOMAIN}', category: 'speed_test' },
    { name: 'WebSpeedTest', url_template: 'https://webspeedtest.cloudinary.com/results/{DOMAIN}', category: 'speed_test' },
    { name: 'Chrome UX Report', url_template: 'https://developer.chrome.com/docs/crux/?url={DOMAIN}', category: 'speed_test' },
    { name: 'TestMySpeed', url_template: 'https://testmysite.io/{DOMAIN}', category: 'speed_test' },
    { name: 'LoadImpact', url_template: 'https://loadimpact.com/load-test?url={DOMAIN}', category: 'speed_test' },
    { name: 'SpeedChecker', url_template: 'https://prowebscraper.com/speed-test/?url={DOMAIN}', category: 'speed_test' },
    { name: 'StatusCake Speed', url_template: 'https://www.statuscake.com/tools/page-speed-test?url={DOMAIN}', category: 'speed_test' },
    { name: 'DataDog Speed', url_template: 'https://www.datadoghq.com/synthetics/test/{DOMAIN}', category: 'speed_test' },
    { name: 'Monitive', url_template: 'https://monitive.com/speedtest/{DOMAIN}', category: 'speed_test' },
    { name: 'Fastly Speed', url_template: 'https://www.fastly.com/network-map/check/{DOMAIN}', category: 'speed_test' },
    { name: 'AkamaiSpeed', url_template: 'https://www.akamai.com/tools/{DOMAIN}', category: 'speed_test' },
    { name: 'HostingAdvice Speed', url_template: 'https://www.hostingadvice.com/how-to/free-website-speed-test/?url={DOMAIN}', category: 'speed_test' },
    { name: 'GreenGeeks Speed', url_template: 'https://www.greengeeks.com/speed-test/?url={DOMAIN}', category: 'speed_test' },
    { name: 'HostPapa Speed', url_template: 'https://www.hostpapa.com/tools/speed-test/?url={DOMAIN}', category: 'speed_test' },
    { name: 'Freshping', url_template: 'https://www.freshworks.com/website-monitoring/is-it-down/?url={DOMAIN}', category: 'speed_test' },
    { name: 'Montastic', url_template: 'https://www.montastic.com/check/{DOMAIN}', category: 'speed_test' },
    { name: 'Uptimia Speed', url_template: 'https://www.uptimia.com/speed-test?url={DOMAIN}', category: 'speed_test' },
    { name: 'PingBear', url_template: 'https://pingbear.com/check/{DOMAIN}', category: 'speed_test' },
    { name: 'SiteUptime', url_template: 'https://siteuptime.com/check/?url={DOMAIN}', category: 'speed_test' },
  ];
}

function getSecurityEndpoints(): EndpointEntry[] {
  return [
    { name: 'SSLLabs', url_template: 'https://www.ssllabs.com/ssltest/analyze.html?d={DOMAIN}', category: 'security_scan' },
    { name: 'SecurityHeaders', url_template: 'https://securityheaders.com/?q=https%3A%2F%2F{DOMAIN}&followRedirects=on', category: 'security_scan' },
    { name: 'VirusTotal', url_template: 'https://www.virustotal.com/gui/domain/{DOMAIN}', category: 'security_scan' },
    { name: 'URLVoid', url_template: 'https://www.urlvoid.com/scan/{DOMAIN}/', category: 'security_scan' },
    { name: 'Sucuri SiteCheck', url_template: 'https://sitecheck.sucuri.net/results/{DOMAIN}', category: 'security_scan' },
    { name: 'Mozilla Observatory', url_template: 'https://observatory.mozilla.org/analyze/{DOMAIN}', category: 'security_scan' },
    { name: 'Hardenize', url_template: 'https://www.hardenize.com/report/{DOMAIN}', category: 'security_scan' },
    { name: 'ImmuniWeb SSL', url_template: 'https://www.immuniweb.com/ssl/?id={DOMAIN}', category: 'security_scan' },
    { name: 'CryptCheck SSL', url_template: 'https://cryptcheck.fr/https/{DOMAIN}', category: 'security_scan' },
    { name: 'SSL Shopper', url_template: 'https://www.sslshopper.com/ssl-checker.html#hostname={DOMAIN}', category: 'security_scan' },
    { name: 'Google Safe Browse', url_template: 'https://transparencyreport.google.com/safe-browsing/search?url={DOMAIN}', category: 'security_scan' },
    { name: 'Norton Safe Web', url_template: 'https://safeweb.norton.com/report/show?url={DOMAIN}', category: 'security_scan' },
    { name: 'McAfee SiteAdvisor', url_template: 'https://www.siteadvisor.com/sitereport.html?url={DOMAIN}', category: 'security_scan' },
    { name: 'PhishTank', url_template: 'https://phishtank.org/phish_search.php?search={DOMAIN}', category: 'security_scan' },
    { name: 'URLhaus', url_template: 'https://urlhaus.abuse.ch/browse.php?search={DOMAIN}', category: 'security_scan' },
    { name: 'ThreatCrowd', url_template: 'https://www.threatcrowd.org/domain.php?domain={DOMAIN}', category: 'security_scan' },
    { name: 'AlienVault OTX', url_template: 'https://otx.alienvault.com/indicator/domain/{DOMAIN}', category: 'security_scan' },
    { name: 'Hybrid Analysis', url_template: 'https://www.hybrid-analysis.com/search?query={DOMAIN}', category: 'security_scan' },
    { name: 'AbuseIPDB', url_template: 'https://www.abuseipdb.com/check/{DOMAIN}', category: 'security_scan' },
    { name: 'Shodan', url_template: 'https://www.shodan.io/search?query={DOMAIN}', category: 'security_scan' },
    { name: 'Censys', url_template: 'https://search.censys.io/hosts?q={DOMAIN}', category: 'security_scan' },
    { name: 'GreyNoise', url_template: 'https://viz.greynoise.io/query/{DOMAIN}', category: 'security_scan' },
    { name: 'ZoomEye', url_template: 'https://www.zoomeye.org/searchResult?q={DOMAIN}', category: 'security_scan' },
    { name: 'ThreatMiner', url_template: 'https://www.threatminer.org/domain.php?q={DOMAIN}', category: 'security_scan' },
    { name: 'RiskIQ', url_template: 'https://community.riskiq.com/search/{DOMAIN}', category: 'security_scan' },
    { name: 'Pulsedive', url_template: 'https://pulsedive.com/indicator/?ioc={DOMAIN}', category: 'security_scan' },
    { name: 'ThreatConnect', url_template: 'https://app.threatconnect.com/auth/indicators?query={DOMAIN}', category: 'security_scan' },
    { name: 'BGPView Security', url_template: 'https://bgpview.io/search/{DOMAIN}', category: 'security_scan' },
    { name: 'Quttera Malware', url_template: 'https://quttera.com/detailed_report/{DOMAIN}', category: 'security_scan' },
    { name: 'SiteLock', url_template: 'https://www.sitelock.com/free-website-scanner/?url={DOMAIN}', category: 'security_scan' },
    { name: 'Detectify', url_template: 'https://detectify.com/external-scan/{DOMAIN}', category: 'security_scan' },
    { name: 'Pentest Tools SSL', url_template: 'https://pentest-tools.com/network-vulnerability-scanning/ssl-tls-scanner?target={DOMAIN}', category: 'security_scan' },
    { name: 'CRTsh Cert', url_template: 'https://crt.sh/?q={DOMAIN}', category: 'security_scan' },
    { name: 'Certificate Search', url_template: 'https://www.certificate-transparency.org/search?q={DOMAIN}', category: 'security_scan' },
    { name: 'SSL Cert Check', url_template: 'https://www.ssllabs.com/ssltest/analyze.html?d={DOMAIN}&hideResults=on', category: 'security_scan' },
    { name: 'CSP Evaluator', url_template: 'https://csp-evaluator.withgoogle.com/?url=https://{DOMAIN}', category: 'security_scan' },
    { name: 'Report URI', url_template: 'https://report-uri.com/home/analyse?url={DOMAIN}', category: 'security_scan' },
    { name: 'Snyk Website', url_template: 'https://snyk.io/website-scanner/?url=https://{DOMAIN}', category: 'security_scan' },
    { name: 'WPScan', url_template: 'https://wpscan.com/wordpress-security-scanner?url={DOMAIN}', category: 'security_scan' },
    { name: 'Wordfence Check', url_template: 'https://www.wordfence.com/free-website-scanner/?url={DOMAIN}', category: 'security_scan' },
    { name: 'UpGuard Score', url_template: 'https://www.upguard.com/security-report/{DOMAIN}', category: 'security_scan' },
    { name: 'BitSight', url_template: 'https://www.bitsight.com/security-ratings/{DOMAIN}', category: 'security_scan' },
    { name: 'SecurityScorecard', url_template: 'https://securityscorecard.com/security-rating/{DOMAIN}', category: 'security_scan' },
    { name: 'Cyberchef', url_template: 'https://gchq.github.io/CyberChef/?input={DOMAIN}', category: 'security_scan' },
    { name: 'BlacklistCheck', url_template: 'https://www.dnsbl.info/dnsbl-database-check.php?domain={DOMAIN}', category: 'security_scan' },
    { name: 'SpamhausCheck', url_template: 'https://check.spamhaus.org/results?query={DOMAIN}', category: 'security_scan' },
    { name: 'SURBL Check', url_template: 'https://www.surbl.org/surbl-analysis?domain={DOMAIN}', category: 'security_scan' },
    { name: 'BarracudaCentral', url_template: 'https://www.barracudacentral.org/lookups/lookup-reputation?lookup_entry={DOMAIN}', category: 'security_scan' },
    { name: 'MultiRBL', url_template: 'https://multirbl.valli.org/lookup/{DOMAIN}.html', category: 'security_scan' },
    { name: 'WebInspector', url_template: 'https://app.webinspector.com/public/reports/free-scan?url={DOMAIN}', category: 'security_scan' },
    { name: 'Tinfoil Security', url_template: 'https://www.tinfoilsecurity.com/scanner?url={DOMAIN}', category: 'security_scan' },
    { name: 'Probely Scanner', url_template: 'https://probely.com/free-scanner?url={DOMAIN}', category: 'security_scan' },
    { name: 'Netsparker', url_template: 'https://www.netsparker.com/online-web-application-security-scanner/?url={DOMAIN}', category: 'security_scan' },
    { name: 'Acunetix Check', url_template: 'https://www.acunetix.com/vulnerability-scanner/free-website-audit/{DOMAIN}/', category: 'security_scan' },
    { name: 'Intruder', url_template: 'https://portal.intruder.io/scan/{DOMAIN}', category: 'security_scan' },
    { name: 'OpenVAS Check', url_template: 'https://www.openvas.org/scan?target={DOMAIN}', category: 'security_scan' },
    { name: 'Nikto Online', url_template: 'https://www.nmmapper.com/sys/tools/nikto/nikto-online/?domain={DOMAIN}', category: 'security_scan' },
    { name: 'WapAlyzer', url_template: 'https://www.wappalyzer.com/lookup/{DOMAIN}/', category: 'security_scan' },
    { name: 'BuiltWith Tech', url_template: 'https://builtwith.com/{DOMAIN}', category: 'security_scan' },
    { name: 'W3Techs', url_template: 'https://w3techs.com/sites/info/{DOMAIN}', category: 'security_scan' },
    { name: 'Netcraft Report', url_template: 'https://sitereport.netcraft.com/?url=https%3A%2F%2F{DOMAIN}', category: 'security_scan' },
    { name: 'Internet Archive SSL', url_template: 'https://web.archive.org/web/*/https://{DOMAIN}', category: 'security_scan' },
    { name: 'TLS Observatory', url_template: 'https://tls-observatory.services.mozilla.com/api/v1/scan?target={DOMAIN}', category: 'security_scan' },
    { name: 'TestTLS', url_template: 'https://testtls.com/{DOMAIN}', category: 'security_scan' },
    { name: 'HTTPSec', url_template: 'https://httpsec.org/scan/{DOMAIN}', category: 'security_scan' },
    { name: 'Grayhat Warfare', url_template: 'https://grayhatwarfare.com/buckets?keywords={DOMAIN}', category: 'security_scan' },
    { name: 'LeakCheck', url_template: 'https://leakcheck.io/result?query={DOMAIN}', category: 'security_scan' },
    { name: 'IntelX', url_template: 'https://intelx.io/?s={DOMAIN}', category: 'security_scan' },
    { name: 'Wayback CDX', url_template: 'https://web.archive.org/cdx/search/cdx?url=*.{DOMAIN}&output=text&fl=original&collapse=urlkey', category: 'security_scan' },
    { name: 'WebCheck', url_template: 'https://web-check.xyz/results/{DOMAIN}', category: 'security_scan' },
  ];
}

function getWebArchiveEndpoints(): EndpointEntry[] {
  return [
    { name: 'Wayback Machine', url_template: 'https://web.archive.org/web/https%3A%2F%2F{DOMAIN}', category: 'web_archive' },
    { name: 'Archive.today', url_template: 'https://archive.ph/newest/https://{DOMAIN}', category: 'web_archive' },
    { name: 'Google Cache', url_template: 'https://webcache.googleusercontent.com/search?q=cache:{DOMAIN}', category: 'web_archive' },
    { name: 'Bing Cache', url_template: 'https://cc.bingj.com/cache.aspx?q={DOMAIN}', category: 'web_archive' },
    { name: 'CachedPage', url_template: 'https://cachedpage.com/cache/{DOMAIN}', category: 'web_archive' },
    { name: 'TimeTravel', url_template: 'https://timetravel.mementoweb.org/timemap/json/https://{DOMAIN}', category: 'web_archive' },
    { name: 'Webrecorder', url_template: 'https://webrecorder.net/?url=https://{DOMAIN}', category: 'web_archive' },
    { name: 'Perma.cc', url_template: 'https://perma.cc/search?q={DOMAIN}', category: 'web_archive' },
    { name: 'ScreenshotMachine', url_template: 'https://screenshotmachine.com/?url={DOMAIN}', category: 'web_archive' },
    { name: 'Archive.org CDX', url_template: 'https://web.archive.org/cdx/search/cdx?url={DOMAIN}&output=text&fl=timestamp,original,mimetype,statuscode', category: 'web_archive' },
    { name: 'CommonCrawl', url_template: 'https://index.commoncrawl.org/CC-MAIN-2024-10-index?url={DOMAIN}&output=json', category: 'web_archive' },
    { name: 'UK Web Archive', url_template: 'https://www.webarchive.org.uk/wayback/archive/*/https://{DOMAIN}', category: 'web_archive' },
    { name: 'Portugal Archive', url_template: 'https://arquivo.pt/url?q={DOMAIN}', category: 'web_archive' },
    { name: 'Iceland Archive', url_template: 'https://vefsafn.is/index.php?page=wp&url={DOMAIN}', category: 'web_archive' },
    { name: 'Stanford WebArchive', url_template: 'https://swap.stanford.edu/*/https://{DOMAIN}', category: 'web_archive' },
    { name: 'LoC WebArchive', url_template: 'https://www.loc.gov/search/?q={DOMAIN}', category: 'web_archive' },
    { name: 'Webarchive.nl', url_template: 'https://webarchive.nl/wayback/*/https://{DOMAIN}', category: 'web_archive' },
    { name: 'Australian Archive', url_template: 'https://pandora.nla.gov.au/pan/?url={DOMAIN}', category: 'web_archive' },
    { name: 'Singapore Archive', url_template: 'https://eresources.nlb.gov.sg/webarchives/search?q={DOMAIN}', category: 'web_archive' },
    { name: 'ArchiveBot', url_template: 'https://archivebot.com/?q={DOMAIN}', category: 'web_archive' },
    { name: 'CacheView', url_template: 'https://cacheview.nl/?url={DOMAIN}', category: 'web_archive' },
    { name: 'OldWeb', url_template: 'https://oldweb.today/?browser=ns4#https://{DOMAIN}', category: 'web_archive' },
    { name: 'Stillio', url_template: 'https://www.stillio.com/website/{DOMAIN}', category: 'web_archive' },
    { name: 'PageFreezer', url_template: 'https://www.pagefreezer.com/archive/{DOMAIN}', category: 'web_archive' },
    { name: 'Conifer Web', url_template: 'https://conifer.rhizome.org/{DOMAIN}', category: 'web_archive' },
    { name: 'Memento Proxy', url_template: 'https://timetravel.mementoweb.org/api/json/https://{DOMAIN}', category: 'web_archive' },
    { name: 'WebCite', url_template: 'https://www.webcitation.org/query?url={DOMAIN}', category: 'web_archive' },
    { name: 'Screenshot API', url_template: 'https://shot.screenshotapi.net/screenshot?url=https://{DOMAIN}', category: 'web_archive' },
    { name: 'ThumbSnap', url_template: 'https://thumbsnap.com/?url={DOMAIN}', category: 'web_archive' },
    { name: 'ShrinkTheWeb', url_template: 'https://images.shrinktheweb.com/xino.php?stwurl={DOMAIN}', category: 'web_archive' },
    { name: 'PagePeeker', url_template: 'https://pagepeeker.com/thumbs.php?size=x&url={DOMAIN}', category: 'web_archive' },
    { name: 'WebThumbnail', url_template: 'https://www.webthumbnail.org/?url=https://{DOMAIN}', category: 'web_archive' },
    { name: 'Screenshots.cloud', url_template: 'https://screenshots.cloud/capture?url=https://{DOMAIN}', category: 'web_archive' },
    { name: 'Capture Website', url_template: 'https://capture.techulus.com/{DOMAIN}', category: 'web_archive' },
  ];
}

function getWebsiteInfoEndpoints(): EndpointEntry[] {
  return [
    { name: 'WorthOfWeb', url_template: 'https://www.worthofweb.com/website-value/{DOMAIN}/', category: 'website_info' },
    { name: 'SimilarTech', url_template: 'https://www.similartech.com/websites/{DOMAIN}', category: 'website_info' },
    { name: 'WorthBlog', url_template: 'https://www.worthblog.com/{DOMAIN}', category: 'website_info' },
    { name: 'EstimatedWorth', url_template: 'https://www.estimatedworth.com/{DOMAIN}', category: 'website_info' },
    { name: 'SitePrice', url_template: 'https://www.siteprice.org/website-worth/{DOMAIN}', category: 'website_info' },
    { name: 'WebsiteOutlook', url_template: 'https://www.websiteoutlook.com/www.{DOMAIN}', category: 'website_info' },
    { name: 'SiteAlerts', url_template: 'https://sitealerts.com/en/report/{DOMAIN}', category: 'website_info' },
    { name: 'CuteStatistics', url_template: 'https://www.cutestat.com/{DOMAIN}', category: 'website_info' },
    { name: 'CloudStatistics', url_template: 'https://cloudstatistics.com/{DOMAIN}', category: 'website_info' },
    { name: 'SiteTrail', url_template: 'https://www.sitetrail.com/{DOMAIN}', category: 'website_info' },
    { name: 'AnalyzeSite', url_template: 'https://www.analyzesite.com/website/{DOMAIN}', category: 'website_info' },
    { name: 'SEOCentro Info', url_template: 'https://www.seocentro.com/tools/seo/domain-age.html?url={DOMAIN}', category: 'website_info' },
    { name: 'DomainAge', url_template: 'https://www.duplichecker.com/domain-age-checker.php?url={DOMAIN}', category: 'website_info' },
    { name: 'Compete', url_template: 'https://www.compete.com/{DOMAIN}', category: 'website_info' },
    { name: 'StatsCounter', url_template: 'https://gs.statcounter.com/{DOMAIN}', category: 'website_info' },
    { name: 'SubDomain Finder', url_template: 'https://subdomainfinder.c99.nl/scans/{DOMAIN}', category: 'website_info' },
    { name: 'IPInfo', url_template: 'https://ipinfo.io/{DOMAIN}', category: 'website_info' },
    { name: 'SiteChecker Tech', url_template: 'https://sitechecker.pro/technology-checker/?url={DOMAIN}', category: 'website_info' },
    { name: 'WebTechSurvey', url_template: 'https://webtechsurvey.com/website/{DOMAIN}', category: 'website_info' },
    { name: 'WhatRuns', url_template: 'https://whatruns.com/{DOMAIN}', category: 'website_info' },
    { name: 'Sitonoly', url_template: 'https://sitonoly.com/{DOMAIN}', category: 'website_info' },
    { name: 'Rescan.io', url_template: 'https://rescan.io/analysis/{DOMAIN}', category: 'website_info' },
    { name: 'URLScan.io', url_template: 'https://urlscan.io/search/#domain:{DOMAIN}', category: 'website_info' },
    { name: 'VirusTotal Info', url_template: 'https://www.virustotal.com/gui/domain/{DOMAIN}/details', category: 'website_info' },
    { name: 'RiskIQ Passive', url_template: 'https://community.riskiq.com/search/{DOMAIN}/summary', category: 'website_info' },
    { name: 'PassiveTotal', url_template: 'https://community.riskiq.com/search/{DOMAIN}/components', category: 'website_info' },
    { name: 'TechLookup', url_template: 'https://techlookup.com/{DOMAIN}', category: 'website_info' },
    { name: 'SiteGur', url_template: 'https://sitegur.com/{DOMAIN}', category: 'website_info' },
    { name: 'WebRank Stats', url_template: 'https://www.webrank.co/{DOMAIN}', category: 'website_info' },
    { name: 'SitePopularity', url_template: 'https://www.sitepopularity.com/{DOMAIN}', category: 'website_info' },
    { name: 'AWebAnalysis', url_template: 'https://www.awebanalysis.com/en/siteinfo/{DOMAIN}/', category: 'website_info' },
    { name: 'DomainsMarket', url_template: 'https://www.domainsmarket.com/market/{DOMAIN}', category: 'website_info' },
    { name: 'DomainTyper', url_template: 'https://domaintyper.com/{DOMAIN}', category: 'website_info' },
    { name: 'EasyCounter', url_template: 'https://www.easycounter.com/{DOMAIN}', category: 'website_info' },
    { name: 'EZWhois', url_template: 'https://ezwhois.com/{DOMAIN}', category: 'website_info' },
    { name: 'FreeSiteReport', url_template: 'https://www.freesitereport.com/{DOMAIN}', category: 'website_info' },
    { name: 'GoogleTrends', url_template: 'https://trends.google.com/trends/explore?q={DOMAIN}', category: 'website_info' },
    { name: 'IndexChecking', url_template: 'https://www.google.com/search?q=site:{DOMAIN}', category: 'website_info' },
    { name: 'CachedPages', url_template: 'https://www.google.com/search?q=cache:{DOMAIN}', category: 'website_info' },
    { name: 'BingIndex', url_template: 'https://www.bing.com/search?q=site:{DOMAIN}', category: 'website_info' },
    { name: 'YandexIndex', url_template: 'https://yandex.com/search/?text=site:{DOMAIN}', category: 'website_info' },
    { name: 'DuckDuckGo', url_template: 'https://duckduckgo.com/?q=site:{DOMAIN}', category: 'website_info' },
    { name: 'BraveSearch', url_template: 'https://search.brave.com/search?q=site:{DOMAIN}', category: 'website_info' },
    { name: 'Ecosia', url_template: 'https://www.ecosia.org/search?q=site:{DOMAIN}', category: 'website_info' },
    { name: 'Qwant', url_template: 'https://www.qwant.com/?q=site:{DOMAIN}', category: 'website_info' },
    { name: 'Mojeek', url_template: 'https://www.mojeek.com/search?q=site:{DOMAIN}', category: 'website_info' },
    { name: 'SearX', url_template: 'https://searx.me/search?q=site:{DOMAIN}', category: 'website_info' },
    { name: 'StartPage', url_template: 'https://www.startpage.com/sp/search?query=site:{DOMAIN}', category: 'website_info' },
    { name: 'GigaBlast', url_template: 'https://www.gigablast.com/search?q=site:{DOMAIN}', category: 'website_info' },
    { name: 'SiteJabber', url_template: 'https://www.sitejabber.com/reviews/{DOMAIN}', category: 'website_info' },
    { name: 'Trustpilot Profile', url_template: 'https://www.trustpilot.com/review/{DOMAIN}', category: 'website_info' },
    { name: 'G2 Software', url_template: 'https://www.g2.com/products/{DOMAIN}/reviews', category: 'website_info' },
    { name: 'Capterra', url_template: 'https://www.capterra.com/search/?query={DOMAIN}', category: 'website_info' },
    { name: 'GetApp', url_template: 'https://www.getapp.com/search/?query={DOMAIN}', category: 'website_info' },
    { name: 'SoftwareAdvice', url_template: 'https://www.softwareadvice.com/search/?q={DOMAIN}', category: 'website_info' },
    { name: 'AlternativeTo', url_template: 'https://alternativeto.net/software/{DOMAIN}/', category: 'website_info' },
    { name: 'ProductHunt', url_template: 'https://www.producthunt.com/search?q={DOMAIN}', category: 'website_info' },
    { name: 'Crunchbase', url_template: 'https://www.crunchbase.com/search/organizations?query={DOMAIN}', category: 'website_info' },
    { name: 'AngelList', url_template: 'https://angel.co/search?q={DOMAIN}', category: 'website_info' },
    { name: 'PitchBook', url_template: 'https://pitchbook.com/profiles/company/{DOMAIN}', category: 'website_info' },
    { name: 'OwlerProfile', url_template: 'https://www.owler.com/company/{DOMAIN}', category: 'website_info' },
    { name: 'ZoomInfo', url_template: 'https://www.zoominfo.com/c/{DOMAIN}', category: 'website_info' },
    { name: 'LinkedIn Company', url_template: 'https://www.linkedin.com/search/results/companies/?keywords={DOMAIN}', category: 'website_info' },
    { name: 'Glassdoor', url_template: 'https://www.glassdoor.com/Reviews/{DOMAIN}-Reviews-E.htm', category: 'website_info' },
    { name: 'BBB Lookup', url_template: 'https://www.bbb.org/search?find_text={DOMAIN}', category: 'website_info' },
    { name: 'Yelp Business', url_template: 'https://www.yelp.com/search?find_desc={DOMAIN}', category: 'website_info' },
    { name: 'Manta', url_template: 'https://www.manta.com/search?search_source=direct&search={DOMAIN}', category: 'website_info' },
    { name: 'YellowPages', url_template: 'https://www.yellowpages.com/search?search_terms={DOMAIN}', category: 'website_info' },
    { name: 'Foursquare', url_template: 'https://foursquare.com/explore?query={DOMAIN}', category: 'website_info' },
    { name: 'ChamberCommerce', url_template: 'https://www.chamberofcommerce.com/search/?q={DOMAIN}', category: 'website_info' },
    { name: 'DnB Company', url_template: 'https://www.dnb.com/business-directory/company-search.html?term={DOMAIN}', category: 'website_info' },
    { name: 'WikipediaSearch', url_template: 'https://en.wikipedia.org/w/index.php?search={DOMAIN}', category: 'website_info' },
    { name: 'RedditSearch', url_template: 'https://www.reddit.com/search/?q={DOMAIN}', category: 'website_info' },
    { name: 'HackerNewsSearch', url_template: 'https://hn.algolia.com/?q={DOMAIN}', category: 'website_info' },
    { name: 'QuoraSearch', url_template: 'https://www.quora.com/search?q={DOMAIN}', category: 'website_info' },
    { name: 'StackOverflow', url_template: 'https://stackoverflow.com/search?q={DOMAIN}', category: 'website_info' },
    { name: 'MediumSearch', url_template: 'https://medium.com/search?q={DOMAIN}', category: 'website_info' },
    { name: 'DevToSearch', url_template: 'https://dev.to/search?q={DOMAIN}', category: 'website_info' },
    { name: 'TwitterSearch', url_template: 'https://twitter.com/search?q={DOMAIN}', category: 'website_info' },
    { name: 'FacebookSearch', url_template: 'https://www.facebook.com/search/top?q={DOMAIN}', category: 'website_info' },
    { name: 'PinterestSearch', url_template: 'https://www.pinterest.com/search/pins/?q={DOMAIN}', category: 'website_info' },
    { name: 'TumblrSearch', url_template: 'https://www.tumblr.com/search/{DOMAIN}', category: 'website_info' },
    { name: 'FlickrSearch', url_template: 'https://www.flickr.com/search/?text={DOMAIN}', category: 'website_info' },
    { name: 'VimeoSearch', url_template: 'https://vimeo.com/search?q={DOMAIN}', category: 'website_info' },
    { name: 'DailymotionSearch', url_template: 'https://www.dailymotion.com/search/{DOMAIN}', category: 'website_info' },
    { name: 'SoundCloudSearch', url_template: 'https://soundcloud.com/search?q={DOMAIN}', category: 'website_info' },
    { name: 'SlideShareSearch', url_template: 'https://www.slideshare.net/search/slideshow?searchfrom=header&q={DOMAIN}', category: 'website_info' },
    { name: 'ScribdSearch', url_template: 'https://www.scribd.com/search?query={DOMAIN}', category: 'website_info' },
    { name: 'IssuuSearch', url_template: 'https://issuu.com/search?q={DOMAIN}', category: 'website_info' },
  ];
}

function getPingEndpoints(): EndpointEntry[] {
  return [
    { name: 'Google Ping', url_template: 'https://www.google.com/ping?sitemap=https://{DOMAIN}/sitemap.xml', category: 'ping_service' },
    { name: 'Bing Webmaster Ping', url_template: 'https://www.bing.com/indexnow?url=https://{DOMAIN}&key=indexnow', category: 'ping_service' },
    { name: 'IndexNow Bing', url_template: 'https://www.bing.com/indexnow?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'IndexNow Yandex', url_template: 'https://yandex.com/indexnow?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'IndexNow Seznam', url_template: 'https://search.seznam.cz/indexnow?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'IndexNow Naver', url_template: 'https://searchadvisor.naver.com/indexnow?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'Pingomatic', url_template: 'https://pingomatic.com/ping/?title=&blogurl=https://{DOMAIN}&rssurl=&chk_blogs=on&chk_feedburner=on&chk_newsgator=on&chk_technorati=on&chk_bloglines=on&chk_google=on', category: 'ping_service' },
    { name: 'Ping-o-Matic2', url_template: 'https://rpc.pingomatic.com/?title=Site&blogurl=https://{DOMAIN}&rssurl=&chk_blogs=on', category: 'ping_service' },
    { name: 'Twingly Ping', url_template: 'https://www.twingly.com/ping?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'Feedburner Ping', url_template: 'https://feedburner.google.com/fb/a/pingSubmit?bloglink=https://{DOMAIN}', category: 'ping_service' },
    { name: 'WeblogUpdates', url_template: 'https://rpc.weblogs.com/pingSiteForm?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'BlogPulse Ping', url_template: 'https://www.blogpulse.com/ping?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'Moreover Ping', url_template: 'https://moreover.com/ping?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'Syndic8 Ping', url_template: 'https://syndic8.com/feedform.php?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'IPings Ping', url_template: 'https://ipings.com/ping/?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'AudioPing', url_template: 'https://audiorss.com/ping?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'BlogDigger Ping', url_template: 'https://www.blogdigger.com/add.jsp?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'FeedShark Ping', url_template: 'https://feedshark.brainbliss.com/?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'PingSitemap', url_template: 'https://www.pingsitemap.com/?action=submit&url=https://{DOMAIN}/sitemap.xml', category: 'ping_service' },
    { name: 'BulkPing', url_template: 'https://bulkping.com/ping/?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'AutoPing', url_template: 'https://autoping.com/ping?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'PingMyURL', url_template: 'https://www.pingmyurl.com/ping/?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'TotalPing', url_template: 'https://totalping.com/pings?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'PingFarm', url_template: 'https://pingfarm.com/index.php?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'MassPing', url_template: 'https://www.massping.com/ping/?url=https://{DOMAIN}', category: 'ping_service' },
    { name: 'BingSitemap Ping', url_template: 'https://www.bing.com/ping?sitemap=https://{DOMAIN}/sitemap.xml', category: 'ping_service' },
    { name: 'YandexPing Sitemap', url_template: 'https://webmaster.yandex.com/ping?sitemap=https://{DOMAIN}/sitemap.xml', category: 'ping_service' },
    { name: 'PubSubHubbub', url_template: 'https://pubsubhubbub.appspot.com/subscribe', category: 'ping_service' },
    { name: 'WebSub Hub', url_template: 'https://websub.rocks/subscribe?hub.topic=https://{DOMAIN}', category: 'ping_service' },
    { name: 'Superfeedr', url_template: 'https://superfeedr.com/subscriber?hub.topic=https://{DOMAIN}', category: 'ping_service' },
  ];
}

function getSocialBookmarkEndpoints(): EndpointEntry[] {
  return [
    { name: 'Reddit Submit', url_template: 'https://www.reddit.com/submit?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Facebook Share', url_template: 'https://www.facebook.com/sharer/sharer.php?u=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Twitter Share', url_template: 'https://twitter.com/intent/tweet?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'LinkedIn Share', url_template: 'https://www.linkedin.com/sharing/share-offsite/?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Pinterest Pin', url_template: 'https://pinterest.com/pin/create/button/?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Tumblr Share', url_template: 'https://www.tumblr.com/share/link?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Mix Share', url_template: 'https://mix.com/add?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Pocket Save', url_template: 'https://getpocket.com/save?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Digg Submit', url_template: 'https://digg.com/submit?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Slashdot Submit', url_template: 'https://slashdot.org/bookmark.pl?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Folkd Bookmark', url_template: 'https://www.folkd.com/page/submit.html?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Scoop.it', url_template: 'https://www.scoop.it/search?type=topic&q={DOMAIN}', category: 'social_bookmark' },
    { name: 'Flipboard', url_template: 'https://share.flipboard.com/bookmarklet/popout?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Buffer Share', url_template: 'https://buffer.com/add?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Instapaper Save', url_template: 'https://www.instapaper.com/hello?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Evernote Clip', url_template: 'https://www.evernote.com/clip.action?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Delicious', url_template: 'https://del.icio.us/post?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Diigo Bookmark', url_template: 'https://www.diigo.com/item/new/bookmark?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Pearltrees', url_template: 'https://www.pearltrees.com/s/{DOMAIN}', category: 'social_bookmark' },
    { name: 'BibSonomy', url_template: 'https://www.bibsonomy.org/url/https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Netvouz', url_template: 'https://www.netvouz.com/action/submitBookmark?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Fark Submit', url_template: 'https://www.fark.com/submit?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'NewsVine', url_template: 'https://www.newsvine.com/_tools/seed&save?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Blogmarks', url_template: 'https://blogmarks.net/my/new.php?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Meneame', url_template: 'https://www.meneame.net/submit?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Wykop', url_template: 'https://www.wykop.pl/remotelink/?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'HackerNews Submit', url_template: 'https://news.ycombinator.com/submitlink?u=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Lobsters', url_template: 'https://lobste.rs/s?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'Lemmy Search', url_template: 'https://lemmy.ml/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'Tildes Search', url_template: 'https://tildes.net/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'VK Share', url_template: 'https://vk.com/share.php?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'OK Share', url_template: 'https://connect.ok.ru/offer?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Weibo Share', url_template: 'https://service.weibo.com/share/share.php?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'LINE Share', url_template: 'https://social-plugins.line.me/lineit/share?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'KakaoStory', url_template: 'https://story.kakao.com/s/share?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Hatena Bookmark', url_template: 'https://b.hatena.ne.jp/entry/s/{DOMAIN}', category: 'social_bookmark' },
    { name: 'Naver Share', url_template: 'https://share.naver.com/web/shareView?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Baidu Share', url_template: 'https://sp0.baidu.com/9_Q4simg2RQJ8t7jm9iCKT-xh_/s?word={DOMAIN}', category: 'social_bookmark' },
    { name: 'Xing Share', url_template: 'https://www.xing.com/spi/shares/new?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Telegram Share', url_template: 'https://t.me/share/url?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'WhatsApp Share', url_template: 'https://api.whatsapp.com/send?text=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Viber Share', url_template: 'viber://forward?text=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Skype Share', url_template: 'https://web.skype.com/share?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'SnapChat', url_template: 'https://www.snapchat.com/scan?attachmentUrl=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'WordPress Blog', url_template: 'https://wordpress.com/read/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'Blogger Search', url_template: 'https://www.blogger.com/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'Ghost Search', url_template: 'https://ghost.org/explore/?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'Substack Search', url_template: 'https://substack.com/search/{DOMAIN}', category: 'social_bookmark' },
    { name: 'Mastodon Search', url_template: 'https://mastodon.social/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'Bluesky Search', url_template: 'https://bsky.app/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'Threads Search', url_template: 'https://www.threads.net/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'Gab Share', url_template: 'https://gab.com/compose?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'Minds Share', url_template: 'https://www.minds.com/newsfeed/subscriptions?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'Diaspora Share', url_template: 'https://share.diasporafoundation.org/?url=https://{DOMAIN}', category: 'social_bookmark' },
    { name: 'GoodReads', url_template: 'https://www.goodreads.com/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'Ello', url_template: 'https://ello.co/search?terms={DOMAIN}', category: 'social_bookmark' },
    { name: '500px', url_template: 'https://500px.com/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'Behance', url_template: 'https://www.behance.net/search/projects?search={DOMAIN}', category: 'social_bookmark' },
    { name: 'Dribbble', url_template: 'https://dribbble.com/search/{DOMAIN}', category: 'social_bookmark' },
    { name: 'DeviantArt', url_template: 'https://www.deviantart.com/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'ArtStation', url_template: 'https://www.artstation.com/search?query={DOMAIN}', category: 'social_bookmark' },
    { name: 'IndieHackers', url_template: 'https://www.indiehackers.com/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'BetaList', url_template: 'https://betalist.com/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'SaaSHub', url_template: 'https://www.saashub.com/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'ToolsForHumans', url_template: 'https://toolsforhumans.ai/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'FuturePedia', url_template: 'https://www.futurepedia.io/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'ThereIsAnAI', url_template: 'https://theresanaiforthat.com/search/?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'AIToolsDirectory', url_template: 'https://aitoolsdirectory.com/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'TopAI Tools', url_template: 'https://topai.tools/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'AItoolsclub', url_template: 'https://www.aitoolsclub.com/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'ToolPilot', url_template: 'https://www.toolpilot.ai/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'EasyWithAI', url_template: 'https://easywithai.com/search/?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'SaaS Genius', url_template: 'https://www.saasgenius.com/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'AppSumo', url_template: 'https://appsumo.com/search/?query={DOMAIN}', category: 'social_bookmark' },
    { name: 'StackShare', url_template: 'https://stackshare.io/search/q={DOMAIN}', category: 'social_bookmark' },
    { name: 'LibHunt', url_template: 'https://www.libhunt.com/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'GitHubSearch', url_template: 'https://github.com/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'GitLabSearch', url_template: 'https://gitlab.com/search?search={DOMAIN}', category: 'social_bookmark' },
    { name: 'NPM Search', url_template: 'https://www.npmjs.com/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'PyPI Search', url_template: 'https://pypi.org/search/?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'DockerHub', url_template: 'https://hub.docker.com/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'SourceForge', url_template: 'https://sourceforge.net/directory/?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'CodeProject', url_template: 'https://www.codeproject.com/search.aspx?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'ResearchGate', url_template: 'https://www.researchgate.net/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'Academia.edu', url_template: 'https://www.academia.edu/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'GoogleScholar', url_template: 'https://scholar.google.com/scholar?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'SemanticScholar', url_template: 'https://www.semanticscholar.org/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'DBLP', url_template: 'https://dblp.org/search?q={DOMAIN}', category: 'social_bookmark' },
    { name: 'ArXiv Search', url_template: 'https://arxiv.org/search/?query={DOMAIN}', category: 'social_bookmark' },
    { name: 'PubMed', url_template: 'https://pubmed.ncbi.nlm.nih.gov/?term={DOMAIN}', category: 'social_bookmark' },
    { name: 'SSRN Search', url_template: 'https://papers.ssrn.com/sol3/results.cfm?RequestTimeout=50000000&txtKey_Words={DOMAIN}', category: 'social_bookmark' },
  ];
}

function getDirectoryEndpoints(): EndpointEntry[] {
  return [
    { name: 'DMOZ', url_template: 'https://dmoz-odp.org/search?q={DOMAIN}', category: 'directory' },
    { name: 'JoeAnt', url_template: 'https://www.joeant.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'Jasmine Directory', url_template: 'https://www.jasminedirectory.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'GoGuides', url_template: 'https://www.goguides.org/search?q={DOMAIN}', category: 'directory' },
    { name: 'SoMuch', url_template: 'https://www.somuch.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'DirectoryWorld', url_template: 'https://www.directoryworld.net/search?q={DOMAIN}', category: 'directory' },
    { name: '1WebDirectory', url_template: 'https://www.1webdirectory.com/search?q={DOMAIN}', category: 'directory' },
    { name: '9Sites', url_template: 'https://www.9sites.net/search?q={DOMAIN}', category: 'directory' },
    { name: 'ABLocal', url_template: 'https://www.ablocal.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'Blogarama', url_template: 'https://www.blogarama.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'BlogCatalog', url_template: 'https://www.blogcatalog.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'BotW', url_template: 'https://botw.org/search?q={DOMAIN}', category: 'directory' },
    { name: 'Business Listing', url_template: 'https://www.businesslisting.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'CitySquares', url_template: 'https://citysquares.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'ClassifiedAds', url_template: 'https://www.classifiedads.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'Cylex', url_template: 'https://www.cylex.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'DirectoryPatch', url_template: 'https://www.directorypatch.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'eLocalListing', url_template: 'https://www.elocallisting.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'EZLocal', url_template: 'https://ezlocal.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'FindOpenDirectory', url_template: 'https://www.findopendirectory.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'FreeAddURL', url_template: 'https://www.freeaddurl.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'GetListed', url_template: 'https://www.getlisted.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'GlobalCatalog', url_template: 'https://www.globalcatalog.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'Hotfrog', url_template: 'https://www.hotfrog.com/search/{DOMAIN}', category: 'directory' },
    { name: 'Hub.biz', url_template: 'https://www.hub.biz/search?q={DOMAIN}', category: 'directory' },
    { name: 'iBegin', url_template: 'https://www.ibegin.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'InfoTiger', url_template: 'https://www.infotiger.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'JustLanded', url_template: 'https://www.justlanded.com/english/search?q={DOMAIN}', category: 'directory' },
    { name: 'LinkCentre', url_template: 'https://www.linkcentre.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'LinkPedia', url_template: 'https://www.linkpedia.net/search?q={DOMAIN}', category: 'directory' },
    { name: 'MasterMoz', url_template: 'https://www.mastermoz.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'MyHuckleberry', url_template: 'https://www.myhuckleberry.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'Noahsplace', url_template: 'https://www.noahsplace.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'OneLocal', url_template: 'https://www.onelocal.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'OpenDirectory', url_template: 'https://www.opendirectory.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'PlaceSlapper', url_template: 'https://www.placeslapper.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'PRLog', url_template: 'https://www.prlog.org/search?q={DOMAIN}', category: 'directory' },
    { name: 'SaaSDirectory', url_template: 'https://www.saasdirectory.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'ShowMeLocal', url_template: 'https://www.showmelocal.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'SmallBizPages', url_template: 'https://www.smallbizpages.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'StartupBuffer', url_template: 'https://startupbuffer.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'StartupStash', url_template: 'https://startupstash.com/search/?q={DOMAIN}', category: 'directory' },
    { name: 'SubmitExpress', url_template: 'https://www.submitexpress.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'TuumCity', url_template: 'https://www.tuumcity.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'ViesLocal', url_template: 'https://www.vieslocal.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'WebDesignDirectory', url_template: 'https://www.webdesign-directory.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'WebLocal', url_template: 'https://www.weblocal.ca/search?q={DOMAIN}', category: 'directory' },
    { name: 'YellowBot', url_template: 'https://www.yellowbot.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'ZipLocal', url_template: 'https://www.ziplocal.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'TopOfTheList', url_template: 'https://www.topofthelist.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'StarOfService', url_template: 'https://www.starofservice.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'TripAdvisor', url_template: 'https://www.tripadvisor.com/Search?q={DOMAIN}', category: 'directory' },
    { name: 'AppleBusinessConnect', url_template: 'https://businessconnect.apple.com/search/{DOMAIN}', category: 'directory' },
    { name: 'BingPlaces', url_template: 'https://www.bingplaces.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'YahooLocal', url_template: 'https://local.yahoo.com/results?p={DOMAIN}', category: 'directory' },
    { name: 'MerchantCircle', url_template: 'https://www.merchantcircle.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'MapQuest', url_template: 'https://www.mapquest.com/search/results?query={DOMAIN}', category: 'directory' },
    { name: 'Superpages', url_template: 'https://www.superpages.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'DexKnows', url_template: 'https://www.dexknows.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'CitySearch', url_template: 'https://www.citysearch.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'Brownbook', url_template: 'https://www.brownbook.net/business/{DOMAIN}/', category: 'directory' },
    { name: 'Fyple', url_template: 'https://www.fyple.com/search/{DOMAIN}/', category: 'directory' },
    { name: 'LocalStack', url_template: 'https://localstack.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'TownSquare', url_template: 'https://townsquare.com/search?q={DOMAIN}', category: 'directory' },
    { name: 'Kompass', url_template: 'https://www.kompass.com/searchCompanies?text={DOMAIN}', category: 'directory' },
    { name: 'ThomasNet', url_template: 'https://www.thomasnet.com/nsearch.html?cov=NA&heading=&what={DOMAIN}', category: 'directory' },
    { name: 'Europages', url_template: 'https://www.europages.co.uk/companies/{DOMAIN}.html', category: 'directory' },
    { name: 'GlobalSpec', url_template: 'https://www.globalspec.com/search?q={DOMAIN}', category: 'directory' },
  ];
}

function getGeneralEndpoints(): EndpointEntry[] {
  return [
    { name: 'Google Search', url_template: 'https://www.google.com/search?q={DOMAIN}', category: 'general' },
    { name: 'Bing Search', url_template: 'https://www.bing.com/search?q={DOMAIN}', category: 'general' },
    { name: 'Yahoo Search', url_template: 'https://search.yahoo.com/search?p={DOMAIN}', category: 'general' },
    { name: 'Yandex Search', url_template: 'https://yandex.com/search/?text={DOMAIN}', category: 'general' },
    { name: 'DuckDuckGo', url_template: 'https://duckduckgo.com/?q={DOMAIN}', category: 'general' },
    { name: 'Baidu Search', url_template: 'https://www.baidu.com/s?wd={DOMAIN}', category: 'general' },
    { name: 'Ask.com', url_template: 'https://www.ask.com/web?q={DOMAIN}', category: 'general' },
    { name: 'AOL Search', url_template: 'https://search.aol.com/aol/search?q={DOMAIN}', category: 'general' },
    { name: 'Ecosia Search', url_template: 'https://www.ecosia.org/search?q={DOMAIN}', category: 'general' },
    { name: 'Brave Search', url_template: 'https://search.brave.com/search?q={DOMAIN}', category: 'general' },
    { name: 'Qwant Search', url_template: 'https://www.qwant.com/?q={DOMAIN}', category: 'general' },
    { name: 'Mojeek Search', url_template: 'https://www.mojeek.com/search?q={DOMAIN}', category: 'general' },
    { name: 'SearX Search', url_template: 'https://searx.me/search?q={DOMAIN}', category: 'general' },
    { name: 'StartPage', url_template: 'https://www.startpage.com/sp/search?query={DOMAIN}', category: 'general' },
    { name: 'GigaBlast Search', url_template: 'https://www.gigablast.com/search?q={DOMAIN}', category: 'general' },
    { name: 'Boardreader', url_template: 'https://boardreader.com/s/{DOMAIN}.html', category: 'general' },
    { name: 'Carrot2', url_template: 'https://search.carrot2.org/#/search/web/{DOMAIN}', category: 'general' },
    { name: 'CC Search', url_template: 'https://search.creativecommons.org/search?q={DOMAIN}', category: 'general' },
    { name: 'Marginalia Search', url_template: 'https://search.marginalia.nu/search?query={DOMAIN}', category: 'general' },
    { name: 'Yep Search', url_template: 'https://yep.com/web?q={DOMAIN}', category: 'general' },
    { name: 'Kagi Search', url_template: 'https://kagi.com/search?q={DOMAIN}', category: 'general' },
    { name: 'Perplexity Search', url_template: 'https://www.perplexity.ai/search?q={DOMAIN}', category: 'general' },
    { name: 'You.com Search', url_template: 'https://you.com/search?q={DOMAIN}', category: 'general' },
    { name: 'Phind Search', url_template: 'https://www.phind.com/search?q={DOMAIN}', category: 'general' },
    { name: 'Archive Search', url_template: 'https://archive.org/search?query={DOMAIN}', category: 'general' },
    { name: 'WikiData', url_template: 'https://www.wikidata.org/w/index.php?search={DOMAIN}', category: 'general' },
    { name: 'OpenStreetMap', url_template: 'https://www.openstreetmap.org/search?query={DOMAIN}', category: 'general' },
    { name: 'InternetDB', url_template: 'https://internetdb.shodan.io/{DOMAIN}', category: 'general' },
    { name: 'HostIO', url_template: 'https://host.io/{DOMAIN}', category: 'general' },
    { name: 'SpyOnWeb', url_template: 'https://spyonweb.com/{DOMAIN}', category: 'general' },
    { name: 'PublicWWW', url_template: 'https://publicwww.com/websites/{DOMAIN}/', category: 'general' },
    { name: 'NerdyData', url_template: 'https://www.nerdydata.com/search?query={DOMAIN}', category: 'general' },
    { name: 'SourceCodeSearch', url_template: 'https://searchcode.com/?q={DOMAIN}', category: 'general' },
    { name: 'Domains Index', url_template: 'https://domainsindex.com/v1/list?search={DOMAIN}', category: 'general' },
    { name: 'WebsiteRank', url_template: 'https://www.website.rank/{DOMAIN}', category: 'general' },
    { name: 'Pagerank Checker', url_template: 'https://checkpagerank.net/?url={DOMAIN}', category: 'general' },
    { name: 'Keywordspy', url_template: 'https://www.keywordspy.com/overview/domain.aspx?q={DOMAIN}', category: 'general' },
    { name: 'MonetizePros', url_template: 'https://monetizepros.com/tools/check/{DOMAIN}', category: 'general' },
    { name: 'URLScan Submit', url_template: 'https://urlscan.io/api/v1/search/?q=domain:{DOMAIN}', category: 'general' },
    { name: 'WebProfiler', url_template: 'https://www.webprofiler.com/{DOMAIN}', category: 'general' },
  ];
}

function getLLMEndpoints(): EndpointEntry[] {
  return [
    { name: 'GoogleRichResults', url_template: 'https://search.google.com/test/rich-results?url=https%3A%2F%2F{DOMAIN}', category: 'llm_indexing' },
    { name: 'GitHub Search', url_template: 'https://github.com/search?q={DOMAIN}&type=repositories', category: 'llm_indexing' },
    { name: 'Google News', url_template: 'https://news.google.com/search?q={DOMAIN}', category: 'llm_indexing' },
    { name: 'Bing News', url_template: 'https://www.bing.com/news/search?q={DOMAIN}', category: 'llm_indexing' },
    { name: 'G2 Reviews', url_template: 'https://www.g2.com/search?q={DOMAIN}', category: 'llm_indexing' },
    { name: 'Crunchbase', url_template: 'https://www.crunchbase.com/textsearch?q={DOMAIN}', category: 'llm_indexing' },
    { name: 'AIScout', url_template: 'https://aiscout.net/search?q={DOMAIN}', category: 'llm_indexing' },
    { name: 'BensBites', url_template: 'https://news.bensbites.co/search?q={DOMAIN}', category: 'llm_indexing' },
    { name: 'SaaSWorthy', url_template: 'https://www.saasworthy.com/search?q={DOMAIN}', category: 'llm_indexing' },
    { name: 'OpenAlex', url_template: 'https://openalex.org/works?search={DOMAIN}', category: 'llm_indexing' },
    { name: 'CrossRef', url_template: 'https://search.crossref.org/search/works?q={DOMAIN}', category: 'llm_indexing' },
    { name: 'Hashnode', url_template: 'https://hashnode.com/search?q={DOMAIN}', category: 'llm_indexing' },
    { name: 'Devpost', url_template: 'https://devpost.com/software/search?query={DOMAIN}', category: 'llm_indexing' },
    { name: 'Hacker Noon', url_template: 'https://hackernoon.com/search?query={DOMAIN}', category: 'llm_indexing' },
    { name: 'DZone', url_template: 'https://dzone.com/search?q={DOMAIN}', category: 'llm_indexing' },
    { name: 'InfoQ', url_template: 'https://www.infoq.com/search.action?queryString={DOMAIN}', category: 'llm_indexing' },
    { name: 'SlashDot', url_template: 'https://slashdot.org/index2.pl?fhfilter={DOMAIN}', category: 'llm_indexing' },
    { name: 'LobstersSearch', url_template: 'https://lobste.rs/search?q={DOMAIN}', category: 'llm_indexing' },
  ];
}
